import {
  Entity,
  Column,
  PrimaryColumn,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToMany,
  JoinTable,
} from 'typeorm';
import { RoleOrmEntity } from './role.orm-entity';

/**
 * UserOrmEntity — TypeORM @Entity
 *
 * Maps the id_users DB table (Migration 001) to a TypeORM entity.
 * This is an INFRASTRUCTURE concern — it lives in infrastructure/persistence/entities/.
 * The Domain User aggregate (modules/identity/domain/user.entity.ts) is separate.
 *
 * ADR-006: TypeORM 0.3.x
 * DB-SCHEMA: id_users (Migration 001)
 * Rule: synchronize:false — table structure comes from migrations ONLY.
 */
@Entity({ name: 'id_users' })
export class UserOrmEntity {
  // id generated by pg_uuidv7 DEFAULT on INSERT — never set by application
  @PrimaryColumn({ type: 'uuid' })
  id!: string;

  @Column({ name: 'full_name', length: 200 })
  fullName!: string;

  // CITEXT — case-insensitive in postgres, stored as-is in TypeORM
  @Column({ name: 'email', type: 'citext', nullable: true, unique: true })
  email!: string | null;

  @Column({ name: 'phone_e164', length: 20, nullable: true, unique: true })
  phoneE164!: string | null;

  // NEVER select this in list queries — only when explicitly needed
  @Column({ name: 'password_hash', length: 255, nullable: true, select: false })
  passwordHash!: string | null;

  @Column({ name: 'avatar_url', type: 'text', nullable: true })
  avatarUrl!: string | null;

  @Column({ name: 'bio', type: 'text', nullable: true })
  bio!: string | null;

  @Column({ name: 'locale', length: 10, default: 'ar' })
  locale!: string;

  @Column({ name: 'theme', length: 20, default: 'system' })
  theme!: string;

  @Column({ name: 'audio_speed', type: 'decimal', precision: 3, scale: 2, default: '1.00' })
  audioSpeed!: number;

  @Column({ name: 'is_suspended', default: false })
  isSuspended!: boolean;

  @Column({ name: 'suspended_at', type: 'timestamptz', nullable: true })
  suspendedAt!: Date | null;

  @Column({ name: 'suspended_by', type: 'uuid', nullable: true })
  suspendedBy!: string | null;

  @Column({ name: 'deleted_at', type: 'timestamptz', nullable: true })
  deletedAt!: Date | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt!: Date;

  @ManyToMany(() => RoleOrmEntity, { eager: false })
  @JoinTable({
    name: 'id_user_roles',
    joinColumn: { name: 'user_id', referencedColumnName: 'id' },
    inverseJoinColumn: { name: 'role_id', referencedColumnName: 'id' },
  })
  roles!: RoleOrmEntity[];
}
