import {
  Injectable,
  NestInterceptor,
  ExecutionContext,
  CallHandler,
  Logger,
} from '@nestjs/common';
import { Observable, tap } from 'rxjs';
import { Request, Response } from 'express';
import { randomUUID } from 'crypto';

/**
 * TraceIdInterceptor
 *
 * P-08: Observable by Default — every request carries a trace_id.
 *
 * - Reads X-Trace-Id from incoming request (set by Nginx from client or generated by Nginx).
 * - Generates one if absent (fallback for direct API calls in dev).
 * - Attaches trace_id to the request object for downstream use (controllers, services, filters).
 * - Echoes trace_id back in the response header.
 * - Logs request + response with duration as structured JSON.
 *
 * OTel-shaped: trace_id field name aligns with OpenTelemetry conventions
 * so a full LGTM stack can be adopted later with zero business-logic change. (ADR-011)
 */
@Injectable()
export class TraceIdInterceptor implements NestInterceptor {
  private readonly logger = new Logger('HTTP');

  intercept(context: ExecutionContext, next: CallHandler): Observable<unknown> {
    const http = context.switchToHttp();
    const request = http.getRequest<Request & { traceId?: string }>();
    const response = http.getResponse<Response>();

    const traceId =
      (request.headers['x-trace-id'] as string) || randomUUID();

    // Make trace_id available to all downstream handlers
    request.traceId = traceId;

    // Echo back so clients can correlate (useful in dev / mobile debugging)
    response.setHeader('X-Trace-Id', traceId);

    const startTime = Date.now();
    const { method, url } = request;

    return next.handle().pipe(
      tap({
        next: () => {
          const duration = Date.now() - startTime;
          this.logger.log({
            traceId,
            method,
            url,
            statusCode: response.statusCode,
            duration,
          });
        },
        error: () => {
          // Errors are logged by GlobalExceptionFilter — no duplicate log here
        },
      }),
    );
  }
}
